# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# https://github.com/r-lib/pak/blob/main/.github/workflows/pkgdown.yaml

# Controls when the action will run. 
on:
  push:
    branches:
      - main
      - master

name: pkgdown-regi

jobs:
  pkgdown:
    runs-on: ubuntu-22.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    name: doc update
    container: rocker/verse
    steps:
      - uses: actions/checkout@v4
      - run: Rscript ./.github/workflows/make_doc.R
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto updating documentation after commit
     
